# Generated by Django 5.1.1 on 2024-10-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client_table',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_max_capacity', models.IntegerField()),
                ('restaurant_current_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'restaurant_table',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('number_of_people', models.IntegerField()),
                ('canceled', models.BooleanField()),
                ('ended', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation_app.client')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_app.restaurant')),
            ],
            options={
                'db_table': 'reservation_table',
            },
        ),
    ]
